flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Chart-1.5.4
- Chart-cairo-1.5.4
- QuickCheck-2.8.1
- StateVar-1.1.0.1
- adjunctions-4.2.2
- alex-3.1.6
- base-orphans-0.4.5
- bifunctors-5.1
- bytestring-lexing-0.5.0.2
- cairo-0.13.1.1
- colour-2.3.3
- comonad-4.2.7.2
- contravariant-1.3.3
- data-accessor-0.2.2.6
- data-accessor-template-0.2.1.12
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.4.4
- dlist-0.7.1.2
- exceptions-0.8.0.2
- free-4.12.1
- gtk2hs-buildtools-0.13.0.5
- hashable-1.2.3.3
- hashtables-1.2.1.0
- kan-extensions-4.2.3
- lens-4.13
- mtl-2.2.1
- old-locale-1.0.0.7
- operational-0.2.3.2
- parallel-3.2.0.6
- parsec-3.1.9
- prelude-extras-0.4.0.2
- primitive-0.6.1.0
- profunctors-5.1.2
- random-1.1
- reflection-2.1
- regex-base-0.93.2
- regex-tdfa-1.2.1
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- stm-2.4.4
- strptime-1.0.10
- tagged-0.8.2
- text-1.2.1.3
- tf-random-0.5
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- utility-ht-0.0.11
- vcs-revision-0.0.2
- vector-0.11.0.0
- void-0.7.1
resolver: ghc-7.10.3
